# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: mysql-storage-master
#   namespace: mysql-poc
# provisioner: kubernetes.io/gce-pd
# parameters:
#   type: pd-ssd
#
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pvc-master
#   namespace: mysql-poc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: mysql-storage-master
# ---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deploy-master
  namespace: mysql-poc
  labels:
    app: mysql
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: master
  template:
    metadata:
      labels:
        app: mysql
        role: master
    spec:
      containers:
      - name: mysql-master
        image: actency/docker-mysql-replication:5.7
        args:
          - "--ignore-db-dir=lost+found"
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "mysqlroot"
          - name: MYSQL_USER
            value: "example_user"
          - name: MYSQL_PASSWORD
            value: "mysqlpwd"
          - name: MYSQL_DATABASE
            value: "example"
          - name: REPLICATION_USER
            value: "replication_user"
          - name: REPLICATION_PASSWORD
            value: "myreplpassword"
        ports:
          - name: mysqlportmaster
            containerPort: 3306
        volumeMounts:
          - name: mysql-vol1
            mountPath: /var/lib/mysql # Storage Volume
      volumes:
        - name: mysql-vol1
          persistentVolumeClaim:
            claimName: mysql-pvc-master
      securityContext:
        fsGroup: 999
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc-master
  namespace: mysql-poc
spec:
  ports:
    - port: 3306
      targetPort: mysqlportmaster
  selector:
    role: master
  type: NodePort
