apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-slave
  namespace: mysql-poc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: mysql-pvc-slave
